### ISSUE TITLE
[1.20.4] NeoForge - Unable to Start - Curio Incompatiability?

### ISSUE THREAD

**Issue by HalestormXV** [RubixDev/Inventorio#348]
Attempting to install this in my modpack on NeoForge 1.20.4. Utilizing version 1.10.3 of this mod. I can't quite tell but maybe a compatibility issue with Curio? 

Here is a partial output of the Debug Log where it starts going balistic.
https://pastebin.com/DtTQYKi3

Here is a partial output in the Latest log where it throws out the Fatal:
https://pastebin.com/Rp9r07yw

Not sure what to say here. I mean I know it is Invetorio because the second i turn it off everything is as smooth as silk. If you want to see the modlist here is the link:
https://modrinth.com/modpack/journey-beyond

It is a shame cause this looks like it would be pretty epic. Plus as far as I am aware no Sorting inventory mods exist yet for NeoForge on 1.20.4 so this would blow up as I know you have a sort feature if i remember correctly from your video.

**Comment by kittymmeow** [comment]
I have a similar issue, so I removed Curios (only using it as a QOL buff for Sophisticated Backpacks, so it was not required for my current set of mods) and Inventorio indeed works flawlessly without Curios installed. I think it's basically guaranteed to be a Curios conflict. In my case it didn't actually crash, just got stuck while loading with no new log entries for an extended period (5+ minutes) until I gave up and killed it.

I saw that #339 was mentioned as fixed in the changelog for 1.10.3, but I wonder if that fix only worked for server instances maybe? I'm running singleplayer. 

I made a new instance with no other mods aside from Inventorio, Curios, Kotlin, and Cloth Config to isolate the issue, so here are the logs:

Minecraft log output: https://pastebin.com/qshLumC8
debug.log: https://pastebin.com/ZWg1WEW5 (extremely similar to yours)

- MultiMC launcher v0.7.0 (should not affect things, but explains some of the content in the console log)
- Minecraft v1.20.4
- NeoForge v20.4.234
- Inventorio v1.10.3
- Curios v[7.4.0+1.20.4] - 2024.04.29
- Kotlin for Forge v4.10.0
- Cloth Config v13.0.121

**Comment by SamHammie** [comment]
Can reproduce.

Minecraft v1.20.1
NeoForge v47.1.106
Inventorio v1.10.3
Curios v[5.11.1+1.20.1]
Kotlin for Forge v4.11.0
Cloth Config v11.1.36

Log output: https://mclo.gs/8FL9bAq
(Yes, other mods were present in my test environment at the time the log was generated. Yes, I tested with just these mods. Yes, the issue persisted. No, it is not related to Sinytra Connector - I triple checked.)
